Improve the postinstall

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,7 +2,7 @@
 
 set -e
 
-CREATE_DATABASE='no'
+CREATE_DATABASE='yes'
 SCRDIR=$(mktemp -dt "$0")
 if [ ! "$?" = "0" ]; then
     exit 1
@@ -27,16 +27,28 @@ if [ $CREATE_GNUSOCIAL_DATABASE ]; then
 fi
 
 if [[ $CREATE_DATABASE != "no" ]]; then
-    ADMIN_PASSWORD='gnusocial'
-    # create a database
-    echo "create database gnusocial;
-CREATE USER 'gnusocialadmin'@'localhost' IDENTIFIED BY '$ADMIN_PASSWORD';
+    ADMIN_PASS='gnusocial'
+    if [ $GNUSOCIAL_ADMIN_PASSWORD ]; then
+        ADMIN_PASS=$GNUSOCIAL_ADMIN_PASSWORD
+    fi
+    MYSQL_ROOT_PASS=
+    if [ $MYSQL_ROOT_PASSWORD ]; then
+        MYSQL_ROOT_PASS=$MYSQL_ROOT_PASSWORD
+    fi
+    if [ $MYSQL_ROOT_PASS ]; then
+        RESULT=$(mysqlshow --user=root --password="$MYSQL_ROOT_PASS" gnusocial| grep -v Wildcard | grep -o gnusocial)
+        if [ "$RESULT" != "gnusocial" ]; then
+            # create a database
+            echo "create database gnusocial;
+CREATE USER 'gnusocialadmin'@'localhost' IDENTIFIED BY '$ADMIN_PASS';
 GRANT ALL PRIVILEGES ON gnusocial.* TO 'gnusocialadmin'@'localhost';
 quit" > $SQL_FILE
-    chmod 600 $SQL_FILE
-    mysql -u root -p < $SQL_FILE
-    if [ ! "$?" = "0" ]; then
-        echo 'Unable to create database for gnusocial'
+            chmod 600 $SQL_FILE
+            mysql -u root --password="$MYSQL_ROOT_PASS" < $SQL_FILE
+            if [ ! "$?" = "0" ]; then
+                echo 'Unable to create database for gnusocial'
+            fi
+        fi
     fi
 fi
 rm -rf $SCRDIR
